apiVersion: apps/v1
kind: Deployment
metadata:
  name: manager-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      serviceAccountName: ui-account
      containers:
      - name: manager
        image: georgeval/manager-service:latest
        ports:
        - containerPort: 5002