apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: manager
spec:
  serviceName: "manager"
  replicas: 3
  selector:
    matchLabels:
      app: manager
  template:
    metadata:
      labels:
        app: manager
    spec:
      containers:
      - name: manager
        image: georgeval/manager-service:latest
        volumeMounts:
        - name: data-storage
          mountPath: /data/pv0001/
        ports:
        - containerPort: 5002
      volumes:
      - name: data-storage
        persistentVolumeClaim:
          claimName: data-minio-0
  volumeClaimTemplates:
  - metadata:
      name: data-minio-0
    spec:
      accessModes: ["ReadWriteMany"]
      resources:
        requests:
          storage: 2Gi
  - metadata:
      name: data-minio-1
    spec:
      accessModes: ["ReadWriteMany"]
      resources:
        requests:
          storage: 2Gi
  - metadata:
      name: data-minio-2
    spec:
      accessModes: ["ReadWriteMany"]
      resources:
        requests:
          storage: 2Gi