apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default 
  name: ui-account
rules: 
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list","create","update","patch","delete","deletecollection"]

  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get","list","create","update","patch","delete","deletecollection"]

  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get","list","create","update","patch","delete","deletecollection"]

  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get","list","create","update","patch","delete","deletecollection"]

  - apiGroups: ["batch", "extensions"]
    resources: ["jobs"]
    verbs: ["get","list","create","update","patch","delete","deletecollection"]

  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get","list","create","update","patch","delete","deletecollection"]

  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get","list","create","update","patch","delete","deletecollection"]