apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: georgeval/ui-service:latest
        ports:
        - containerPort: 5002
        env:
        - name: AUTH_URL
          value: "http://auth-service:5000"
        - name: MANAGER_URL
          value: "http://manager-service:5001"
